project:
  type: website

website:
  title: "NYX VA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.qmd"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.qmd"
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.qmd"
        - text: "Hands-on Exercise 7"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.qmd"
        - text: "Hands-on Exercise 8 (Week5: Network)"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.qmd"
        - text: "Hands-on Exercise 9"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.qmd"
        - text: "Hands-on Exercise 10"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.qmd"
        - text: "Hands-on Exercise 11"
          href: "Hands-on_Ex/Hands-on_Ex11/Hands-on_Ex11.qmd"
        - text: "Hands-on Exercise 12"
          href: "Hands-on_Ex/Hands-on_Ex12/Hands-on_Ex12.qmd"
        - text: "Hands-on Exercise 13"
          href: "Hands-on_Ex/Hands-on_Ex13/Hands-on_Ex13.qmd"
          
         
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.qmd"
        - text: "In-class Exercise 3"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.qmd"
        - text: "In-class Exercise 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.qmd"
        - text: "In-class Exercise 5"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.qmd"
        - text: "In-class Exercise 6"
          href: "In-class_Ex/In-class_Ex06/In-class_Ex06.qmd"
         
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.qmd"
        - text: "Take-home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.qmd"
         
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      
  sidebar:
    style: 'docked'
    background: light
    contents:
      - section: 'Hands-on Exercise'
        contents:
          - Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
          - Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
          - Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd
          - Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.qmd
          - Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.qmd
          - Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.qmd
          - Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.qmd
          - Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.qmd
          - Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.qmd
          - Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.qmd
          - Hands-on_Ex/Hands-on_Ex11/Hands-on_Ex11.qmd
          - Hands-on_Ex/Hands-on_Ex12/Hands-on_Ex12.qmd
          - Hands-on_Ex/Hands-on_Ex13/Hands-on_Ex13.qmd

            
      - section: 'In-class Exercise'
        contents:
          - In-class_Ex/In-class_Ex01/In-class_Ex01.qmd
          - In-class_Ex/In-class_Ex03/In-class_Ex03.qmd
          - In-class_Ex/In-class_Ex04/In-class_Ex04.qmd
          - In-class_Ex/In-class_Ex05/In-class_Ex05.qmd
          - In-class_Ex/In-class_Ex06/In-class_Ex06.qmd
            
      - section: 'Take-home Exercise'
        contents:
          - Take-home_Ex/Take-home_Ex01/Take-home_Ex01.qmd
          - Take-home_Ex/Take-home_Ex02/Take-home_Ex02.qmd
          - Take-home_Ex/Take-home_Ex03/Take-home_Ex03.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

