---
title: "In-class_Ex01"
author: "NeoYX"
editor: visual
execute: 
  freeze: auto
  warning: false
  #echo: false
  html:
    code-fold: false
    code-overflow: wrap
    code-summary: "Show the code"
    code-line-numbers: true
---

```{r}
pacman:: p_load(tidyverse)
```

```{r}
exam_data <- read_csv("data1/Exam_data.csv")
```

Task 1: Plotting a bar chart

Reference website : [R bloggers](https://www.r-bloggers.com/2022/07/how-to-change-background-color-in-ggplot2-3/) (How to change the background colour of ggplot2?)

```{r}
ggplot(data=exam_data,
       aes(x=RACE)) +
  geom_bar() +
  coord_flip() +
  
  theme(panel.background = element_rect(fill ='lightblue', color ='black',linetype = 'dotted'),
        panel.grid.major = element_line (color= 'red', linetype = 'dotted'),
        panel.grid.minor = element_line (colour='green', size= 2, linetype = 'dotted'),
        plot.title= element_text(size=rel(2))) +
  ggtitle('Number of students by Race') +
  labs(y='Number of students')
```

```{r}

```
